version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gridmate-postgres
    environment:
      POSTGRES_USER: gridmate
      POSTGRES_PASSWORD: gridmate_dev_password
      POSTGRES_DB: gridmate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gridmate"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gridmate-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gridmate-api
    environment:
      # Database configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: gridmate
      DB_PASSWORD: gridmate_dev_password
      DB_NAME: gridmate_db
      DB_SSL_MODE: disable
      
      # Application configuration
      PORT: 8080
      ENV: development
      LOG_LEVEL: debug
      
      # JWT configuration
      JWT_SECRET: your-dev-secret-key-change-in-production
      JWT_EXPIRY: 24h
      
      # CORS configuration
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001
      
      # API Keys (for development)
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/vendor
    command: go run cmd/api/main.go
    networks:
      - gridmate-network

  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: gridmate-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gridmate-network

  # Optional: ChromaDB for vector storage
  chromadb:
    image: chromadb/chroma:latest
    container_name: gridmate-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      IS_PERSISTENT: TRUE
      ANONYMIZED_TELEMETRY: FALSE
    networks:
      - gridmate-network

volumes:
  postgres_data:
  redis_data:
  chromadb_data:

networks:
  gridmate-network:
    driver: bridge